import type { Locale } from "@/lib/i18n";

const fields: Record<string, { fa: string; ar: string }> = {
  id: { fa: "شناسه", ar: "المعرّف" },
  buyerId: { fa: "شناسه خریدار", ar: "معرّف المشتري" },
  sellerId: { fa: "شناسه فروشنده", ar: "معرّف البائع" },
  checkoutId: { fa: "شناسه تسویه‌حساب", ar: "معرّف إتمام الشراء" },
  itemId: { fa: "شناسه قلم سفارش", ar: "معرّف عنصر الطلب" },
  offerId: { fa: "شناسه پیشنهاد فروش", ar: "معرّف العرض" },
  groupId: { fa: "شناسه گروه پرداخت", ar: "معرّف مجموعة الدفع" },
  grantId: { fa: "شناسه دسترسی سرویس", ar: "معرّف صلاحية الخدمة" },
  fullName: { fa: "نام و نام خانوادگی", ar: "الاسم الكامل" },
  name: { fa: "نام", ar: "الاسم" },
  username: { fa: "نام کاربری", ar: "اسم المستخدم" },
  email: { fa: "ایمیل", ar: "البريد الإلكتروني" },
  phoneNumber: { fa: "شماره تماس", ar: "رقم الهاتف" },
  role: { fa: "نقش", ar: "الدور" },
  owner: { fa: "مالک فروشگاه", ar: "صاحب المتجر" },
  buyer: { fa: "خریدار", ar: "المشتري" },
  seller: { fa: "فروشنده", ar: "البائع" },
  shopName: { fa: "نام فروشگاه", ar: "اسم المتجر" },
  invited: { fa: "دعوت‌شده", ar: "مدعو" },
  approved: { fa: "تأییدشده", ar: "معتمد" },
  suspendedAt: { fa: "زمان تعلیق", ar: "وقت التعليق" },
  status: { fa: "وضعیت", ar: "الحالة" },
  fromStatus: { fa: "وضعیت پیشین", ar: "الحالة السابقة" },
  toStatus: { fa: "وضعیت جدید", ar: "الحالة الجديدة" },
  trafficSource: { fa: "منبع ورود مشتری", ar: "مصدر العميل" },
  currency: { fa: "ارز", ar: "العملة" },
  totalAmount: { fa: "مبلغ کل", ar: "المبلغ الإجمالي" },
  grossAmount: { fa: "مبلغ ناخالص", ar: "المبلغ الإجمالي" },
  commissionAmount: { fa: "مبلغ کارمزد", ar: "مبلغ العمولة" },
  holdbackAmount: { fa: "مبلغ ذخیره", ar: "المبلغ المحتجز" },
  payableAmount: { fa: "مبلغ قابل پرداخت", ar: "المبلغ المستحق" },
  commissionRate: { fa: "نرخ کارمزد", ar: "نسبة العمولة" },
  holdbackRate: { fa: "نرخ ذخیره", ar: "نسبة الاحتجاز" },
  amount: { fa: "مبلغ", ar: "المبلغ" },
  orderAmount: { fa: "سهم این سفارش", ar: "حصة هذا الطلب" },
  unitPrice: { fa: "قیمت واحد", ar: "سعر الوحدة" },
  quantity: { fa: "تعداد", ar: "الكمية" },
  productType: { fa: "نوع محصول", ar: "نوع المنتج" },
  productTitle: { fa: "نام محصول", ar: "اسم المنتج" },
  serviceNote: { fa: "یادداشت خدمت", ar: "ملاحظة الخدمة" },
  digitalDelivery: { fa: "تحویل فایل", ar: "تسليم الملف" },
  digitalDeliveries: { fa: "دانلود فایل‌ها", ar: "تنزيل الملفات" },
  digitalFiles: { fa: "فایل‌های خریداری‌شده", ar: "الملفات المشتراة" },
  downloadUrl: { fa: "مسیر دریافت فایل", ar: "مسار تنزيل الملف" },
  destinationHost: { fa: "میزبان فایل", ar: "مضيف الملف" },
  maxDownloads: { fa: "حداکثر دریافت", ar: "الحد الأقصى للتنزيل" },
  downloadCount: { fa: "تعداد دریافت", ar: "عدد مرات التنزيل" },
  lastAccessedAt: { fa: "آخرین دریافت", ar: "آخر تنزيل" },
  recipientName: { fa: "نام گیرنده", ar: "اسم المستلم" },
  province: { fa: "استان", ar: "المحافظة" },
  city: { fa: "شهر", ar: "المدينة" },
  addressLine: { fa: "نشانی", ar: "العنوان" },
  postalCode: { fa: "کد پستی", ar: "الرمز البريدي" },
  carrier: { fa: "شرکت حمل", ar: "شركة الشحن" },
  trackingCode: { fa: "کد رهگیری", ar: "رمز التتبع" },
  shippedAt: { fa: "زمان ارسال", ar: "وقت الشحن" },
  shippingAddressCreatedAt: { fa: "زمان ثبت نشانی", ar: "وقت تسجيل العنوان" },
  shipmentUpdatedAt: { fa: "آخرین تغییر ارسال", ar: "آخر تحديث للشحنة" },
  externalOrderId: { fa: "شناسه سفارش حمل", ar: "معرّف طلب الشحن" },
  providerOrderId: { fa: "شناسه سفارش نزد سرویس", ar: "معرّف الطلب لدى الخدمة" },
  amadastTrackingCode: { fa: "کد رهگیری آمادست", ar: "رمز تتبع أمادست" },
  providerTrackingCode: { fa: "کد رهگیری سرویس", ar: "رمز تتبع المزود" },
  providerOrderReference: { fa: "شناسه سفارش سرویس", ar: "مرجع طلب المزود" },
  courierTrackingCode: { fa: "کد رهگیری پیک", ar: "رمز تتبع المندوب" },
  courierTitle: { fa: "نام پیک", ar: "اسم المندوب" },
  attemptCount: { fa: "تعداد تلاش‌ها", ar: "عدد المحاولات" },
  attempts: { fa: "تلاش‌ها", ar: "المحاولات" },
  lastAttemptedAt: { fa: "آخرین تلاش", ar: "آخر محاولة" },
  registeredAt: { fa: "زمان ثبت", ar: "وقت التسجيل" },
  trackingSyncedAt: { fa: "آخرین همگام‌سازی رهگیری", ar: "آخر مزامنة للتتبع" },
  errorCode: { fa: "کد خطا", ar: "رمز الخطأ" },
  failureCode: { fa: "کد خطای پرداخت", ar: "رمز فشل الدفع" },
  lastError: { fa: "آخرین خطا", ar: "آخر خطأ" },
  inventory: { fa: "رزرو موجودی", ar: "حجز المخزون" },
  digital: { fa: "دسترسی فایل", ar: "الوصول إلى الملف" },
  bridge: { fa: "پردازش بریج", ar: "تنفيذ بريدج" },
  expiresAt: { fa: "زمان انقضا", ar: "وقت الانتهاء" },
  service: { fa: "سرویس", ar: "الخدمة" },
  externalServiceId: { fa: "شناسه سرویس خارجی", ar: "معرّف الخدمة الخارجية" },
  mode: { fa: "روش پردازش", ar: "طريقة التنفيذ" },
  providerReference: { fa: "شناسه مرجع سرویس", ar: "مرجع الخدمة" },
  submitAttempts: { fa: "تلاش برای ثبت", ar: "محاولات الإرسال" },
  manualRetryCount: { fa: "تلاش دوباره دستی", ar: "إعادات المحاولة اليدوية" },
  nextAttemptAt: { fa: "تلاش بعدی", ar: "المحاولة التالية" },
  submittedAt: { fa: "زمان ارسال به سرویس", ar: "وقت الإرسال إلى الخدمة" },
  completedAt: { fa: "زمان تکمیل", ar: "وقت الإكمال" },
  input: { fa: "داده‌های ورودی", ar: "بيانات الإدخال" },
  result: { fa: "نتیجه", ar: "النتيجة" },
  action: { fa: "عملیات", ar: "الإجراء" },
  outcome: { fa: "نتیجه تلاش", ar: "نتيجة المحاولة" },
  at: { fa: "زمان رویداد", ar: "وقت الحدث" },
  events: { fa: "رویدادها", ar: "الأحداث" },
  actor: { fa: "انجام‌دهنده", ar: "المنفذ" },
  provider: { fa: "درگاه یا سرویس", ar: "مزود الخدمة" },
  refund: { fa: "بازپرداخت", ar: "الاسترداد" },
  initiationStartedAt: { fa: "آغاز پرداخت", ar: "بدء الدفع" },
  verifiedAt: { fa: "زمان تأیید پرداخت", ar: "وقت تأكيد الدفع" },
  refundedAt: { fa: "زمان بازپرداخت", ar: "وقت الاسترداد" },
  requestedAt: { fa: "زمان درخواست", ar: "وقت الطلب" },
  approvedAt: { fa: "زمان تأیید", ar: "وقت الاعتماد" },
  settledAt: { fa: "زمان تسویه", ar: "وقت التسوية" },
  publishedAt: { fa: "زمان انتشار", ar: "وقت النشر" },
  deliveredAt: { fa: "زمان تحویل", ar: "وقت التسليم" },
  consumer: { fa: "دریافت‌کننده رویداد", ar: "مستقبل الحدث" },
  deliveries: { fa: "ارسال‌ها", ar: "عمليات التسليم" },
  groups: { fa: "گروه‌ها", ar: "المجموعات" },
  type: { fa: "نوع رویداد", ar: "نوع الحدث" },
  createdAt: { fa: "زمان ایجاد", ar: "وقت الإنشاء" },
  updatedAt: { fa: "آخرین تغییر", ar: "آخر تحديث" }
};

const values: Record<string, { fa: string; ar: string }> = {
  pending: { fa: "در انتظار", ar: "معلق" },
  paid: { fa: "پرداخت‌شده", ar: "مدفوع" },
  processing: { fa: "در حال پردازش", ar: "قيد المعالجة" },
  shipped: { fa: "ارسال‌شده", ar: "تم الشحن" },
  awaiting_confirmation: { fa: "در انتظار تأیید", ar: "بانتظار التأكيد" },
  delivered: { fa: "تحویل‌شده", ar: "تم التسليم" },
  cancelled: { fa: "لغوشده", ar: "ملغى" },
  draft: { fa: "پیش‌نویس", ar: "مسودة" },
  requested: { fa: "درخواست‌شده", ar: "مطلوب" },
  approved: { fa: "تأییدشده", ar: "معتمد" },
  settled: { fa: "تسویه‌شده", ar: "تمت التسوية" },
  disputed: { fa: "مورد اختلاف", ar: "متنازع عليه" },
  created: { fa: "ایجادشده", ar: "تم الإنشاء" },
  initiating: { fa: "در حال آغاز", ar: "قيد البدء" },
  initiation_unknown: { fa: "نتیجه آغاز نامشخص", ar: "نتيجة البدء غير معروفة" },
  succeeded: { fa: "موفق", ar: "ناجح" },
  refund_pending: { fa: "در انتظار بازپرداخت", ar: "بانتظار الاسترداد" },
  refund_unknown: { fa: "وضعیت بازپرداخت نامشخص", ar: "حالة الاسترداد غير معروفة" },
  failed: { fa: "ناموفق", ar: "فاشل" },
  refunded: { fa: "بازپرداخت‌شده", ar: "تم الاسترداد" },
  unknown: { fa: "نامشخص", ar: "غير معروف" },
  pending_payment: { fa: "در انتظار پرداخت", ar: "بانتظار الدفع" },
  partially_paid: { fa: "بخشی پرداخت‌شده", ar: "مدفوع جزئياً" },
  expired: { fa: "منقضی‌شده", ar: "منتهي الصلاحية" },
  active: { fa: "فعال", ar: "نشط" },
  committed: { fa: "ثبت قطعی", ar: "مؤكد" },
  released: { fa: "آزادشده", ar: "تم تحريره" },
  waiting_payment: { fa: "در انتظار پرداخت", ar: "بانتظار الدفع" },
  queued: { fa: "در صف", ar: "في قائمة الانتظار" },
  submitting: { fa: "در حال ارسال", ar: "جارٍ الإرسال" },
  submitted: { fa: "ارسال‌شده به سرویس", ar: "أرسل إلى الخدمة" },
  registering: { fa: "در حال ثبت ارسال", ar: "جارٍ تسجيل الشحنة" },
  registered: { fa: "ارسال ثبت‌شده", ar: "تم تسجيل الشحنة" },
  tracking_available: { fa: "رهگیری آماده است", ar: "التتبع متاح" },
  polling: { fa: "در حال بررسی نتیجه", ar: "جارٍ التحقق من النتيجة" },
  manual_required: { fa: "نیازمند رسیدگی دستی", ar: "يتطلب معالجة يدوية" },
  refund_requested: { fa: "بازپرداخت درخواست‌شده", ar: "طُلب الاسترداد" },
  automatic: { fa: "خودکار", ar: "تلقائي" },
  manual: { fa: "دستی", ar: "يدوي" },
  digital: { fa: "دیجیتال", ar: "رقمي" },
  physical: { fa: "فیزیکی", ar: "مادي" },
  service: { fa: "خدمت", ar: "خدمة" },
  bridge: { fa: "بریج", ar: "بريدج" },
  buyer: { fa: "خریدار", ar: "المشتري" },
  "seller-admin": { fa: "مدیر فروشنده", ar: "مدير البائع" },
  "seller-staff": { fa: "کارمند فروشنده", ar: "موظف البائع" },
  "platform-admin": { fa: "مدیر پلتفرم", ar: "مدير المنصة" },
  "platform-staff": { fa: "کارمند پلتفرم", ar: "موظف المنصة" },
  direct: { fa: "مستقیم", ar: "مباشر" },
  "order.created": { fa: "سفارش ثبت شد", ar: "أُنشئ الطلب" },
  "order.paid": { fa: "سفارش پرداخت شد", ar: "دُفع الطلب" },
  "order.status.updated": { fa: "وضعیت سفارش تغییر کرد", ar: "تغيرت حالة الطلب" },
  "bridge.fulfillment.succeeded": { fa: "پردازش بریج موفق بود", ar: "نجح تنفيذ بريدج" },
  "bridge.fulfillment.failed": { fa: "پردازش بریج ناموفق بود", ar: "فشل تنفيذ بريدج" },
  "bridge.refund.requested": { fa: "بازپرداخت بریج درخواست شد", ar: "طُلب استرداد بريدج" },
  submit: { fa: "ارسال به سرویس", ar: "الإرسال إلى الخدمة" },
  poll: { fa: "بررسی نتیجه", ar: "التحقق من النتيجة" },
  retry: { fa: "تلاش دوباره", ar: "إعادة المحاولة" },
  complete: { fa: "تکمیل", ar: "الإكمال" },
  success: { fa: "موفق", ar: "ناجح" },
  failure: { fa: "ناموفق", ar: "فاشل" }
};

const translatedValueKeys = new Set(["status", "fromStatus", "toStatus", "productType", "mode", "role", "trafficSource", "outcome", "action", "type"]);
const ltrKeys = new Set(["id", "buyerId", "sellerId", "checkoutId", "itemId", "offerId", "groupId", "grantId", "providerOrderId", "providerOrderReference", "externalOrderId", "externalServiceId", "providerReference", "email", "username", "phoneNumber", "postalCode", "trackingCode", "providerTrackingCode", "amadastTrackingCode", "courierTrackingCode", "downloadUrl", "destinationHost", "currency", "errorCode", "failureCode"]);

export function orderFieldLabel(key: string, locale: Locale) {
  if (locale !== "en" && fields[key]) return fields[key][locale];
  return key.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/_/g, " ").replace(/^./, (letter) => letter.toUpperCase());
}

export function orderValueLabel(key: string, value: string, locale: Locale) {
  if (locale !== "en" && translatedValueKeys.has(key) && values[value]) return values[value][locale];
  return value;
}

export function orderValueDirection(key: string, value: unknown): "ltr" | "auto" {
  if (ltrKeys.has(key) || (typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(value))) return "ltr";
  return "auto";
}
