import type { Locale } from "@/lib/i18n";

const words: Record<string, readonly [string, string, string]> = {
  pending: ["Pending", "در انتظار", "قيد الانتظار"],
  pending_payment: ["Awaiting payment", "در انتظار پرداخت", "بانتظار الدفع"],
  waiting_payment: ["Awaiting payment", "در انتظار پرداخت", "بانتظار الدفع"],
  partially_paid: ["Partly paid", "بخشی از مبلغ پرداخت شده", "مدفوع جزئياً"],
  paid: ["Paid", "پرداخت شده", "مدفوع"],
  processing: ["In progress", "در حال انجام", "قيد التنفيذ"],
  shipped: ["Shipped", "ارسال شده", "تم الشحن"],
  awaiting_confirmation: ["Awaiting confirmation", "در انتظار تأیید", "بانتظار التأكيد"],
  delivered: ["Delivered", "تحویل داده شده", "تم التسليم"],
  cancelled: ["Cancelled", "لغو شده", "ملغى"],
  created: ["Created", "ثبت شده", "تم الإنشاء"],
  initiating: ["Starting payment", "در حال شروع پرداخت", "جارٍ بدء الدفع"],
  initiation_unknown: ["Payment start unconfirmed", "شروع پرداخت تأیید نشده", "بدء الدفع غير مؤكد"],
  succeeded: ["Successful", "انجام شده", "ناجح"],
  failed: ["Failed", "ناموفق", "فشل"],
  refund_pending: ["Awaiting refund", "در انتظار بازگشت وجه", "بانتظار الاسترداد"],
  refund_unknown: ["Refund unconfirmed", "بازگشت وجه تأیید نشده", "الاسترداد غير مؤكد"],
  refunded: ["Refunded", "وجه برگشت داده شده", "تم رد المبلغ"],
  expired: ["Expired", "مهلت تمام شده", "انتهت الصلاحية"],
  consumed: ["Code used", "رمز استفاده شده", "تم استخدام الرمز"],
  sending: ["Sending", "در حال ارسال", "جارٍ الإرسال"],
  sent: ["Sent", "ارسال شده", "تم الإرسال"],
  active: ["Active", "فعال", "نشط"],
  inactive: ["Inactive", "غیرفعال", "غير نشط"],
  approved: ["Approved", "تأیید شده", "معتمد"],
  rejected: ["Rejected", "رد شده", "مرفوض"],
  pending_review: ["Awaiting review", "در انتظار بررسی", "بانتظار المراجعة"],
  published: ["Published", "منتشر شده", "منشور"],
  hidden: ["Hidden", "پنهان شده", "مخفي"],
  draft: ["Draft", "پیش‌نویس", "مسودة"],
  unknown: ["Result unconfirmed", "نتیجه مشخص نشده", "النتيجة غير مؤكدة"],
  create: ["Created", "ایجاد شده", "تم الإنشاء"],
  update: ["Updated", "ویرایش شده", "تم التعديل"],
  delete: ["Deleted", "حذف شده", "تم الحذف"],
  publish: ["Published", "منتشر شده", "تم النشر"],
  archive: ["Archived", "بایگانی شده", "تمت الأرشفة"],
  archived: ["Archived", "بایگانی شده", "مؤرشف"],
  queued: ["Queued", "در صف انجام", "في قائمة الانتظار"],
  revoked: ["Access revoked", "دسترسی لغو شده", "تم إلغاء الوصول"],
  orders: ["Order", "سفارش", "طلب"],
  checkouts: ["Purchase attempt", "تلاش برای خرید", "محاولة شراء"],
  payment_attempts: ["Payment attempt", "تلاش برای پرداخت", "محاولة دفع"],
  auth_sessions: ["Account login", "ورود به حساب", "تسجيل دخول"],
  admin_user_profile_changes: ["Profile change", "تغییر اطلاعات کاربر", "تغيير البيانات"],
  comments: ["Comment", "دیدگاه", "تعليق"],
  seller_memberships: ["Shop membership", "عضویت در فروشگاه", "عضوية متجر"],
  digital_entitlements: ["Purchased file access", "دسترسی به فایل خریداری‌شده", "وصول إلى ملف مشترى"],
  ai_conversations: ["AI conversation", "گفت‌وگوی هوش مصنوعی", "محادثة ذكاء اصطناعي"],
  order_events: ["Order change", "تغییر سفارش", "تغيير الطلب"],
  payouts: ["Seller payout", "تسویه فروشنده", "مستحقات البائع"],
  addresses: ["Saved address", "نشانی ذخیره‌شده", "عنوان محفوظ"],
  admin: ["Shop manager", "مدیر فروشگاه", "مدير المتجر"],
  staff: ["Shop staff", "همکار فروشگاه", "موظف المتجر"],
  product: ["Product", "محصول", "منتج"],
  blog: ["Blog post", "مطلب وبلاگ", "مقالة"],
  "Payout action": ["Payout change", "تغییر تسویه فروشنده", "تغيير مستحقات البائع"],
  "Product change": ["Product change", "تغییر محصول", "تغيير المنتج"],
  "Blog change": ["Blog post change", "تغییر مطلب وبلاگ", "تغيير المقالة"],
  "Blog moderation": ["Blog review", "بررسی مطلب وبلاگ", "مراجعة المقالة"],
  "AI audit": ["AI activity", "فعالیت هوش مصنوعی", "نشاط الذكاء الاصطناعي"],
  "Security policy": ["Security settings change", "تغییر تنظیمات امنیت", "تغيير إعدادات الأمان"],
  "Login settings": ["Login settings change", "تغییر تنظیمات ورود", "تغيير إعدادات الدخول"],
  "SMS settings": ["SMS settings change", "تغییر تنظیمات پیامک", "تغيير إعدادات الرسائل"],
  "Shipping settings": ["Shipping settings change", "تغییر تنظیمات ارسال", "تغيير إعدادات الشحن"],
  "Seller shipping": ["Seller shipping change", "تغییر ارسال فروشنده", "تغيير شحن البائع"],
  "USD rate": ["Exchange rate change", "تغییر نرخ دلار", "تغيير سعر الصرف"],
  "Payment method": ["Payment method change", "تغییر روش پرداخت", "تغيير طريقة الدفع"],
  "Comment moderation": ["Comment review", "بررسی دیدگاه", "مراجعة التعليق"],
  "Bridge access": ["Service information access", "مشاهده اطلاعات سرویس", "عرض معلومات الخدمة"],
};

export function historyTerm(value: string, locale: Locale) {
  return words[value]?.[locale === "fa" ? 1 : locale === "ar" ? 2 : 0] ?? value;
}

export const historyHelp = {
  en: {
    technical: "Technical details", technicalHelp: "Original values and identifiers for support follow-up.",
    orders: "What the user ordered, payment details, and delivery progress.",
    checkouts: "Purchase attempts, including unpaid or expired purchases. A purchase may include several orders.",
    payments: "Each payment attempt and its result. One order can have several attempts.",
    entitlements: "Purchased files the user can download and their download limits.",
    comments: "Comments written or reported by this user.", communications: "Text messages and one-time login code requests for the user’s current phone number.",
    sessions: "Login sessions and whether they are still valid. A valid session does not mean the user is online.",
    ai: "AI conversations, message counts, and processing activity.", seller: "Shops this user belongs to and their access level.",
    activity: "Changes and actions made by this user across the site.", profile: "Which contact details changed, with previous and current values.",
    related: "Additional linked records for detailed follow-up; some may also appear in other categories.",
    attempts: "Code entry attempts", template: "Message template code", source: "Original record title", raw: "Original data",
  },
  fa: {
    technical: "جزئیات فنی", technicalHelp: "مقادیر اصلی و شناسه‌ها برای پیگیری با پشتیبانی.",
    orders: "خریدهای کاربر، جزئیات پرداخت و مراحل تحویل سفارش.",
    checkouts: "خریدهای شروع‌شده، حتی اگر پرداخت نشده یا مهلتشان تمام شده باشد. هر خرید ممکن است چند سفارش داشته باشد.",
    payments: "هر بار تلاش برای پرداخت و نتیجه آن؛ یک سفارش ممکن است چند تلاش پرداخت داشته باشد.",
    entitlements: "فایل‌های خریداری‌شده و تعداد دفعاتی که کاربر می‌تواند آن‌ها را دانلود کند.",
    comments: "دیدگاه‌هایی که این کاربر نوشته یا گزارش کرده است.", communications: "پیامک‌ها و درخواست‌های رمز ورود مربوط به شماره تماس فعلی کاربر.",
    sessions: "ورودهای کاربر و اعتبار آن‌ها؛ معتبر بودن ورود به معنی آنلاین بودن کاربر نیست.",
    ai: "گفت‌وگوهای کاربر با هوش مصنوعی، تعداد پیام‌ها و درخواست‌های پردازش.", seller: "فروشگاه‌هایی که کاربر در آن‌ها عضو است و سطح دسترسی او.",
    activity: "تغییرات و اقدام‌هایی که این کاربر در سایت انجام داده است.", profile: "اطلاعات تماسی که تغییر کرده‌اند، همراه با مقدار قبلی و فعلی.",
    related: "سوابق تکمیلی برای پیگیری دقیق‌تر؛ بعضی موارد در بخش‌های دیگر هم نمایش داده می‌شوند.",
    attempts: "تعداد تلاش برای وارد کردن رمز", template: "کد قالب پیامک", source: "عنوان اصلی سابقه", raw: "داده‌های اصلی",
  },
  ar: {
    technical: "تفاصيل تقنية", technicalHelp: "القيم الأصلية والمعرّفات للمتابعة مع الدعم.",
    orders: "مشتريات المستخدم وتفاصيل الدفع ومراحل التسليم.", checkouts: "محاولات الشراء، بما فيها غير المدفوعة والمنتهية. قد تشمل عدة طلبات.",
    payments: "كل محاولة دفع ونتيجتها؛ قد يتضمن الطلب عدة محاولات.", entitlements: "الملفات المشتراة وحدود تنزيلها.",
    comments: "تعليقات كتبها المستخدم أو أبلغ عنها.", communications: "الرسائل وطلبات رمز الدخول لرقم المستخدم الحالي.",
    sessions: "جلسات الدخول وصلاحيتها. الجلسة الصالحة لا تعني أن المستخدم متصل الآن.", ai: "محادثات الذكاء الاصطناعي وعدد الرسائل وطلبات المعالجة.",
    seller: "المتاجر التي ينتمي إليها المستخدم ومستوى وصوله.", activity: "التغييرات والإجراءات التي أجراها المستخدم.",
    profile: "بيانات الاتصال التي تغيرت مع القيم السابقة والحالية.", related: "سجلات إضافية للمتابعة؛ قد تظهر أيضاً في أقسام أخرى.",
    attempts: "محاولات إدخال الرمز", template: "رمز قالب الرسالة", source: "عنوان السجل الأصلي", raw: "البيانات الأصلية",
  },
} as const;
