export const lifecycleCopy = {
  en: {
    emailBlock: "Add an email address in the profile before assigning a non-buyer role or receiving seller ownership.",
    title: "Roles & account access", status: "Account status", active: "Active", blocked: "Blocked", deletion_pending: "Deletion in progress", deleted: "Deleted",
    buyer: "Buyer", seller_staff: "Seller staff", seller_admin: "Seller admin", platform_staff: "Platform staff", platform_admin: "Platform admin",
    role: "Global role", permissions: "Platform permissions", seller: "Seller", owner: "Canonical seller owner", changeRole: "Change role", block: "Block account", unblock: "Unblock account", remove: "Delete account", cancel: "Cancel", save: "Confirm change", next: "Review confirmation", back: "Back", loading: "Loading…", retry: "Try again", search: "Search", more: "Load more", select: "Select an account or seller", reason: "Reason", password: "Your administrator password", confirmation: "Type this exact identifier", saved: "Change saved. Active sessions have ended.", error: "The request failed. Refresh the details, check your confirmation and try again.",
    ownerBlock: "Transfer canonical seller ownership before demoting this owner or moving them to another seller.", roleHint: "Role changes replace delegated permissions and active seller membership. All sessions end; a blocked account stays blocked.", blockHint: "Blocking ends all sessions and prevents sign-in. The seller and public content remain visible. Unblocking is manual.", deleteHint: "Deletion is irreversible. Public ownership transfers to the selected account; financial and audit history stay attached to the original identities. The source seller is suspended while the job runs.", mergeHint: "The destination keeps its listings, coupon codes, permissions and settings on conflict. Source conflicts are archived or deactivated. Bridge credentials are not transferred; affected listings require manual reconfiguration.", frozenHint: "The source account and participating sellers cannot be edited during transfer. Failed jobs remain locked until an explicit retry succeeds.", replacement: "Replacement owner", destination: "Destination seller", handoff: "Hand over the source seller", content: "Transfer public content", merge: "Merge into the selected seller", counts: "Impact", blockers: "Outstanding obligations — deletion is blocked", conflicts: "Expected conflicts", review: "Review ownership transfer", start: "Permanently delete and transfer", progress: "Deletion progress", queued: "Queued", running: "Running", failed: "Failed — review before retrying", completed: "Completed", transferred: "Transferred", archived: "Archived / removed", skipped: "Skipped", conflicted: "Conflicted", none: "None", required: "Select a replacement before continuing.", audit: "Account events",
    products: "Products", listings: "Listings", coupons: "Coupons", articles: "Articles", articleMedia: "Article media", comments: "Comments", assignments: "Comment assignments", privateAi: "Private AI conversations", profileHistory: "Private profile snapshots", otp: "OTP challenges", communications: "SMS records", sellerProducts: "Products under seller ownership", sellerListings: "Seller listings", orders: "Orders / disputes", checkouts: "Checkouts", payments: "Payments", refunds: "Refunds", payouts: "Payouts", fulfillment: "Fulfillment", shipping: "Shipping", aiRuns: "Active AI tasks", bridge: "Bridge listings", finalize: "Final verification",
    vendors_manage: "Manage sellers", catalog_view: "View catalog", orders_manage: "Manage orders", payouts_manage: "Manage payouts", blog_manage: "Manage articles", uploads_manage: "Manage uploads"
  },
  fa: {
    emailBlock: "پیش از واگذاری مالکیت فروشنده یا انتخاب نقشی جز خریدار، ایمیل کاربر را در اطلاعات حساب ثبت کنید.",
    title: "نقش و دسترسی حساب", status: "وضعیت حساب", active: "فعال", blocked: "مسدود", deletion_pending: "در حال حذف", deleted: "حذف‌شده",
    buyer: "خریدار", seller_staff: "همکار فروشنده", seller_admin: "مدیر فروشنده", platform_staff: "همکار پلتفرم", platform_admin: "مدیر پلتفرم",
    role: "نقش کاربر", permissions: "دسترسی‌های پلتفرم", seller: "فروشنده", owner: "مالک اصلی فروشنده", changeRole: "تغییر نقش", block: "مسدود کردن حساب", unblock: "رفع مسدودی", remove: "حذف حساب", cancel: "انصراف", save: "تأیید تغییر", next: "بررسی و تأیید", back: "بازگشت", loading: "در حال بارگذاری…", retry: "تلاش دوباره", search: "جست‌وجو", more: "نمایش بیشتر", select: "کاربر یا فروشنده را انتخاب کنید", reason: "دلیل", password: "رمز عبور مدیر شما", confirmation: "این شناسه را دقیق وارد کنید", saved: "تغییر ذخیره شد. نشست‌های فعال کاربر پایان یافت.", error: "درخواست انجام نشد. اطلاعات را دوباره بارگذاری کنید و پس از بررسی تأییدیه، دوباره تلاش کنید.",
    ownerBlock: "پیش از تغییر نقش مالک یا انتقال او به فروشنده‌ای دیگر، مالکیت اصلی فروشنده را واگذار کنید.", roleHint: "با تغییر نقش، دسترسی‌های پلتفرم و عضویت فعال فروشنده جایگزین می‌شوند. همه نشست‌ها پایان می‌یابند؛ حساب مسدود همچنان مسدود می‌ماند.", blockHint: "مسدودسازی همه نشست‌ها را می‌بندد و جلوی ورود را می‌گیرد. فروشنده و محتوای عمومی همچنان نمایش داده می‌شوند. رفع مسدودی باید دستی انجام شود.", deleteHint: "حذف حساب برگشت‌پذیر نیست. مالکیت محتوای عمومی منتقل می‌شود، اما سوابق مالی و مدیریتی به نام‌های اصلی باقی می‌مانند. فروشنده مبدأ تا پایان انتقال تعلیق می‌شود.", mergeHint: "در موارد تکراری، آگهی‌ها، کدهای تخفیف، دسترسی‌ها و تنظیمات مقصد حفظ می‌شوند. موارد تکراری مبدأ بایگانی یا غیرفعال می‌شوند. اطلاعات اتصال بریج منتقل نمی‌شود و آگهی‌های مربوط به تنظیم دوباره نیاز دارند.", frozenHint: "در طول انتقال، حساب مبدأ و فروشنده‌های درگیر قابل ویرایش نیستند. اگر کار ناموفق شود، تا تلاش دوباره قفل می‌مانند.", replacement: "مالک جایگزین", destination: "فروشنده مقصد", handoff: "واگذاری فروشنده مبدأ", content: "انتقال محتوای عمومی", merge: "ادغام در فروشنده انتخاب‌شده", counts: "موارد تحت تأثیر", blockers: "تعهدات باز — حذف امکان‌پذیر نیست", conflicts: "موارد تکراری و تعارض‌ها", review: "بررسی انتقال مالکیت", start: "حذف دائمی و انتقال", progress: "روند حذف", queued: "در صف", running: "در حال اجرا", failed: "ناموفق — پیش از تلاش دوباره بررسی کنید", completed: "انجام شد", transferred: "منتقل‌شده", archived: "بایگانی یا پاک‌شده", skipped: "بدون تغییر", conflicted: "دارای تعارض", none: "ندارد", required: "برای ادامه، مالک جایگزین را انتخاب کنید.", audit: "سوابق تغییر حساب",
    products: "محصولات", listings: "آگهی‌ها", coupons: "کدهای تخفیف", articles: "مقاله‌ها", articleMedia: "رسانه‌های مقاله", comments: "دیدگاه‌ها", assignments: "ارجاع دیدگاه‌ها", privateAi: "گفت‌وگوهای خصوصی هوش مصنوعی", profileHistory: "نسخه‌های قبلی اطلاعات شخصی", otp: "رمزهای یک‌بارمصرف", communications: "سوابق پیامک", sellerProducts: "محصولات تحت مالکیت فروشنده", sellerListings: "آگهی‌های فروشنده", orders: "سفارش‌ها و اختلاف‌ها", checkouts: "خریدهای ناتمام", payments: "پرداخت‌ها", refunds: "بازپرداخت‌ها", payouts: "تسویه‌ها", fulfillment: "انجام سفارش", shipping: "ارسال", aiRuns: "کارهای فعال هوش مصنوعی", bridge: "آگهی‌های بریج", finalize: "بررسی نهایی",
    vendors_manage: "مدیریت فروشنده‌ها", catalog_view: "مشاهده محصولات", orders_manage: "مدیریت سفارش‌ها", payouts_manage: "مدیریت تسویه‌ها", blog_manage: "مدیریت مقاله‌ها", uploads_manage: "مدیریت فایل‌ها"
  },
  ar: {
    emailBlock: "أضف بريداً إلكترونياً إلى الملف قبل تعيين دور غير المشتري أو استلام ملكية البائع.",
    title: "الأدوار والوصول إلى الحساب", status: "حالة الحساب", active: "نشط", blocked: "محظور", deletion_pending: "الحذف جارٍ", deleted: "محذوف",
    buyer: "مشترٍ", seller_staff: "موظف بائع", seller_admin: "مدير بائع", platform_staff: "موظف منصة", platform_admin: "مدير منصة",
    role: "الدور العام", permissions: "صلاحيات المنصة", seller: "البائع", owner: "المالك الرئيسي للبائع", changeRole: "تغيير الدور", block: "حظر الحساب", unblock: "رفع الحظر", remove: "حذف الحساب", cancel: "إلغاء", save: "تأكيد التغيير", next: "مراجعة التأكيد", back: "رجوع", loading: "جارٍ التحميل…", retry: "إعادة المحاولة", search: "بحث", more: "عرض المزيد", select: "اختر حساباً أو بائعاً", reason: "السبب", password: "كلمة مرور المسؤول", confirmation: "اكتب هذا المعرّف كما هو", saved: "تم حفظ التغيير وإنهاء الجلسات النشطة.", error: "تعذر تنفيذ الطلب. حدّث البيانات وتحقق من التأكيد ثم حاول مجدداً.",
    ownerBlock: "انقل الملكية الرئيسية للبائع قبل خفض دور المالك أو نقله إلى بائع آخر.", roleHint: "يستبدل تغيير الدور الصلاحيات المفوضة وعضوية البائع النشطة. تنتهي جميع الجلسات؛ ويبقى الحساب المحظور محظوراً.", blockHint: "ينهي الحظر جميع الجلسات ويمنع الدخول. يبقى البائع والمحتوى العام ظاهرين. رفع الحظر يدوي.", deleteHint: "الحذف نهائي. تنتقل ملكية المحتوى العام، وتبقى السجلات المالية وسجلات التدقيق مرتبطة بالهويات الأصلية. يُعلّق البائع المصدر أثناء النقل.", mergeHint: "عند التعارض، تُحفظ عروض الوجهة ورموز الخصم وصلاحياتها وإعداداتها. تُؤرشف عروض المصدر المتعارضة وتُعطّل قسائمه المتكررة. لا تُنقل بيانات اتصال الجسر؛ وتحتاج عروضه إلى إعادة إعداد يدوية.", frozenHint: "لا يمكن تعديل الحساب المصدر أو البائعين المشاركين أثناء النقل. تبقى المهام الفاشلة مقفلة حتى نجاح إعادة المحاولة.", replacement: "المالك البديل", destination: "البائع الوجهة", handoff: "تسليم ملكية البائع المصدر", content: "نقل المحتوى العام", merge: "دمج في البائع المحدد", counts: "الأثر", blockers: "التزامات مفتوحة — الحذف غير متاح", conflicts: "التعارضات المتوقعة", review: "مراجعة نقل الملكية", start: "الحذف النهائي والنقل", progress: "تقدم الحذف", queued: "في الانتظار", running: "قيد التنفيذ", failed: "فشل — راجع قبل إعادة المحاولة", completed: "مكتمل", transferred: "منقول", archived: "مؤرشف / محذوف", skipped: "دون تغيير", conflicted: "متعارض", none: "لا يوجد", required: "اختر مالكاً بديلاً للمتابعة.", audit: "سجل تغييرات الحساب",
    products: "المنتجات", listings: "العروض", coupons: "القسائم", articles: "المقالات", articleMedia: "وسائط المقالات", comments: "التعليقات", assignments: "إسناد التعليقات", privateAi: "محادثات الذكاء الاصطناعي الخاصة", profileHistory: "نسخ البيانات الشخصية", otp: "رموز التحقق", communications: "سجلات الرسائل", sellerProducts: "منتجات البائع", sellerListings: "عروض البائع", orders: "الطلبات والنزاعات", checkouts: "عمليات الشراء", payments: "المدفوعات", refunds: "المبالغ المستردة", payouts: "التسويات", fulfillment: "تنفيذ الطلبات", shipping: "الشحن", aiRuns: "مهام الذكاء الاصطناعي النشطة", bridge: "عروض الجسر", finalize: "التحقق النهائي",
    vendors_manage: "إدارة البائعين", catalog_view: "عرض المنتجات", orders_manage: "إدارة الطلبات", payouts_manage: "إدارة التسويات", blog_manage: "إدارة المقالات", uploads_manage: "إدارة الملفات"
  }
} as const;
