// This file is generated automatically by Next.js
// Do not edit this file manually

// Type definitions for Next.js routes

/**
 * Internal types used by the Next.js router and Link component.
 * These types are not meant to be used directly.
 * @internal
 */
declare namespace __next_route_internal_types__ {
  type SearchOrHash = `?${string}` | `#${string}`
  type WithProtocol = `${string}:${string}`

  type Suffix = '' | SearchOrHash

  type SafeSlug<S extends string> = S extends `${string}/${string}`
    ? never
    : S extends `${string}${SearchOrHash}`
    ? never
    : S extends ''
    ? never
    : S

  type CatchAllSlug<S extends string> = S extends `${string}${SearchOrHash}`
    ? never
    : S extends ''
    ? never
    : S

  type OptionalCatchAllSlug<S extends string> =
    S extends `${string}${SearchOrHash}` ? never : S

  type StaticRoutes = 
    | `/api/auth/login-methods` // ../../src/app/api/auth/login-methods/route.ts
    | `/sitemap.xml` // ../../src/app/sitemap.xml/route.ts
  type DynamicRoutes<T extends string = string> = 
    | `/${SafeSlug<T>}` // ../../src/app/[locale]/page.tsx
    | `/${SafeSlug<T>}/account` // ../../src/app/[locale]/account/page.tsx
    | `/${SafeSlug<T>}/account/leaderboard` // ../../src/app/[locale]/account/leaderboard/page.tsx
    | `/${SafeSlug<T>}/account/orders` // ../../src/app/[locale]/account/orders/page.tsx
    | `/${SafeSlug<T>}/account/settings` // ../../src/app/[locale]/account/settings/page.tsx
    | `/${SafeSlug<T>}/admin` // ../../src/app/[locale]/admin/page.tsx
    | `/${SafeSlug<T>}/admin/ai` // ../../src/app/[locale]/admin/ai/page.tsx
    | `/${SafeSlug<T>}/admin/ai/assistant` // ../../src/app/[locale]/admin/ai/assistant/page.tsx
    | `/${SafeSlug<T>}/admin/ai/models` // ../../src/app/[locale]/admin/ai/models/page.tsx
    | `/${SafeSlug<T>}/admin/blog` // ../../src/app/[locale]/admin/blog/page.tsx
    | `/${SafeSlug<T>}/admin/blog/${SafeSlug<T>}` // ../../src/app/[locale]/admin/blog/[id]/page.tsx
    | `/${SafeSlug<T>}/admin/bridge` // ../../src/app/[locale]/admin/bridge/page.tsx
    | `/${SafeSlug<T>}/admin/coupons` // ../../src/app/[locale]/admin/coupons/page.tsx
    | `/${SafeSlug<T>}/admin/orders` // ../../src/app/[locale]/admin/orders/page.tsx
    | `/${SafeSlug<T>}/admin/orders/${SafeSlug<T>}` // ../../src/app/[locale]/admin/orders/[id]/page.tsx
    | `/${SafeSlug<T>}/admin/payments` // ../../src/app/[locale]/admin/payments/page.tsx
    | `/${SafeSlug<T>}/admin/payments/methods` // ../../src/app/[locale]/admin/payments/methods/page.tsx
    | `/${SafeSlug<T>}/admin/payments/transactions` // ../../src/app/[locale]/admin/payments/transactions/page.tsx
    | `/${SafeSlug<T>}/admin/product-changes` // ../../src/app/[locale]/admin/product-changes/page.tsx
    | `/${SafeSlug<T>}/admin/products` // ../../src/app/[locale]/admin/products/page.tsx
    | `/${SafeSlug<T>}/admin/products/${SafeSlug<T>}` // ../../src/app/[locale]/admin/products/[id]/page.tsx
    | `/${SafeSlug<T>}/admin/security/captcha` // ../../src/app/[locale]/admin/security/captcha/page.tsx
    | `/${SafeSlug<T>}/admin/security/login` // ../../src/app/[locale]/admin/security/login/page.tsx
    | `/${SafeSlug<T>}/admin/security/rate-limit` // ../../src/app/[locale]/admin/security/rate-limit/page.tsx
    | `/${SafeSlug<T>}/admin/settings/auth` // ../../src/app/[locale]/admin/settings/auth/page.tsx
    | `/${SafeSlug<T>}/admin/settings/backup` // ../../src/app/[locale]/admin/settings/backup/page.tsx
    | `/${SafeSlug<T>}/admin/settings/blog-sidebar` // ../../src/app/[locale]/admin/settings/blog-sidebar/page.tsx
    | `/${SafeSlug<T>}/admin/settings/comments` // ../../src/app/[locale]/admin/settings/comments/page.tsx
    | `/${SafeSlug<T>}/admin/settings/goghdi` // ../../src/app/[locale]/admin/settings/goghdi/page.tsx
    | `/${SafeSlug<T>}/admin/settings/homepage` // ../../src/app/[locale]/admin/settings/homepage/page.tsx
    | `/${SafeSlug<T>}/admin/settings/notice` // ../../src/app/[locale]/admin/settings/notice/page.tsx
    | `/${SafeSlug<T>}/admin/settings/seo` // ../../src/app/[locale]/admin/settings/seo/page.tsx
    | `/${SafeSlug<T>}/admin/settings/shipping` // ../../src/app/[locale]/admin/settings/shipping/page.tsx
    | `/${SafeSlug<T>}/admin/settings/sms` // ../../src/app/[locale]/admin/settings/sms/page.tsx
    | `/${SafeSlug<T>}/admin/settings/stories` // ../../src/app/[locale]/admin/settings/stories/page.tsx
    | `/${SafeSlug<T>}/admin/settings/usd` // ../../src/app/[locale]/admin/settings/usd/page.tsx
    | `/${SafeSlug<T>}/admin/staff` // ../../src/app/[locale]/admin/staff/page.tsx
    | `/${SafeSlug<T>}/admin/statistics` // ../../src/app/[locale]/admin/statistics/page.tsx
    | `/${SafeSlug<T>}/admin/uploads` // ../../src/app/[locale]/admin/uploads/page.tsx
    | `/${SafeSlug<T>}/admin/users` // ../../src/app/[locale]/admin/users/page.tsx
    | `/${SafeSlug<T>}/admin/vendors` // ../../src/app/[locale]/admin/vendors/page.tsx
    | `/${SafeSlug<T>}/blog` // ../../src/app/[locale]/blog/page.tsx
    | `/${SafeSlug<T>}/blog/${SafeSlug<T>}` // ../../src/app/[locale]/blog/[slug]/page.tsx
    | `/${SafeSlug<T>}/blog/category/${SafeSlug<T>}` // ../../src/app/[locale]/blog/category/[slug]/page.tsx
    | `/${SafeSlug<T>}/blog/feed.xml` // ../../src/app/[locale]/blog/feed.xml/route.ts
    | `/${SafeSlug<T>}/blog/rss.xml` // ../../src/app/[locale]/blog/rss.xml/route.ts
    | `/${SafeSlug<T>}/blog/seller/${SafeSlug<T>}` // ../../src/app/[locale]/blog/seller/[sellerId]/page.tsx
    | `/${SafeSlug<T>}/blog/tag/${SafeSlug<T>}` // ../../src/app/[locale]/blog/tag/[slug]/page.tsx
    | `/${SafeSlug<T>}/cart` // ../../src/app/[locale]/cart/page.tsx
    | `/${SafeSlug<T>}/checkout/${SafeSlug<T>}` // ../../src/app/[locale]/checkout/[id]/page.tsx
    | `/${SafeSlug<T>}/contact-us` // ../../src/app/[locale]/contact-us/page.tsx
    | `/${SafeSlug<T>}/experts/${SafeSlug<T>}` // ../../src/app/[locale]/experts/[id]/page.tsx
    | `/${SafeSlug<T>}/login` // ../../src/app/[locale]/login/page.tsx
    | `/${SafeSlug<T>}/orders/${SafeSlug<T>}` // ../../src/app/[locale]/orders/[id]/page.tsx
    | `/${SafeSlug<T>}/pay/local/${SafeSlug<T>}` // ../../src/app/[locale]/pay/local/[authority]/page.tsx
    | `/${SafeSlug<T>}/products` // ../../src/app/[locale]/products/page.tsx
    | `/${SafeSlug<T>}/products/${SafeSlug<T>}` // ../../src/app/[locale]/products/[slug]/page.tsx
    | `/${SafeSlug<T>}/seller-dashboard` // ../../src/app/[locale]/seller-dashboard/page.tsx
    | `/${SafeSlug<T>}/seller-dashboard/blog/${SafeSlug<T>}` // ../../src/app/[locale]/seller-dashboard/blog/[id]/page.tsx
    | `/${SafeSlug<T>}/seller-dashboard/bridge` // ../../src/app/[locale]/seller-dashboard/bridge/page.tsx
    | `/${SafeSlug<T>}/seller-dashboard/bridge/products/new` // ../../src/app/[locale]/seller-dashboard/bridge/products/new/page.tsx
    | `/${SafeSlug<T>}/seller-dashboard/comments` // ../../src/app/[locale]/seller-dashboard/comments/page.tsx
    | `/${SafeSlug<T>}/seller-dashboard/products/new` // ../../src/app/[locale]/seller-dashboard/products/new/page.tsx
    | `/${SafeSlug<T>}/staff-setup/${SafeSlug<T>}` // ../../src/app/[locale]/staff-setup/[token]/page.tsx
    | `/homepage-images/${SafeSlug<T>}` // ../../src/app/homepage-images/[filename]/route.ts
    | `/media/${SafeSlug<T>}/${SafeSlug<T>}` // ../../src/app/media/[assetId]/[filename]/route.ts
    | `/sitemap/${SafeSlug<T>}` // ../../src/app/sitemap/[id]/route.ts

  type RouteImpl<T> = 
    | StaticRoutes
    | SearchOrHash
    | WithProtocol
    | `${StaticRoutes}${SearchOrHash}`
    | (T extends `${DynamicRoutes<infer _>}${Suffix}` ? T : never)
    
}

declare module 'next' {
  export { default } from 'next/types.js'
  export * from 'next/types.js'

  export type Route<T extends string = string> =
    __next_route_internal_types__.RouteImpl<T>
}

declare module 'next/link' {
  export { useLinkStatus } from 'next/dist/client/link.js'

  import type { LinkProps as OriginalLinkProps } from 'next/dist/client/link.js'
  import type { AnchorHTMLAttributes, DetailedHTMLProps } from 'react'
  import type { UrlObject } from 'url'

  type LinkRestProps = Omit<
    Omit<
      DetailedHTMLProps<
        AnchorHTMLAttributes<HTMLAnchorElement>,
        HTMLAnchorElement
      >,
      keyof OriginalLinkProps
    > &
      OriginalLinkProps,
    'href'
  >

  export type LinkProps<RouteInferType> = LinkRestProps & {
    /**
     * The path or URL to navigate to. This is the only required prop. It can also be an object.
     * @see https://nextjs.org/docs/api-reference/next/link
     */
    href: __next_route_internal_types__.RouteImpl<RouteInferType> | UrlObject
  }

  export default function Link<RouteType>(props: LinkProps<RouteType>): JSX.Element
}

declare module 'next/navigation' {
  export * from 'next/dist/client/components/navigation.js'

  import type { NavigateOptions, AppRouterInstance as OriginalAppRouterInstance } from 'next/dist/shared/lib/app-router-context.shared-runtime.js'
  import type { RedirectType } from 'next/dist/client/components/redirect-error.js'
  
  interface AppRouterInstance extends OriginalAppRouterInstance {
    /**
     * Navigate to the provided href.
     * Pushes a new history entry.
     */
    push<RouteType>(href: __next_route_internal_types__.RouteImpl<RouteType>, options?: NavigateOptions): void
    /**
     * Navigate to the provided href.
     * Replaces the current history entry.
     */
    replace<RouteType>(href: __next_route_internal_types__.RouteImpl<RouteType>, options?: NavigateOptions): void
    /**
     * Prefetch the provided href.
     */
    prefetch<RouteType>(href: __next_route_internal_types__.RouteImpl<RouteType>): void
  }

  export function useRouter(): AppRouterInstance;
  
  /**
   * This function allows you to redirect the user to another URL. It can be used in
   * [Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components),
   * [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers), and
   * [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations).
   *
   * - In a Server Component, this will insert a meta tag to redirect the user to the target page.
   * - In a Route Handler, it will serve a 307 to the caller.
   * - In a Server Action, it will perform a client-side navigation when JavaScript is available or serve a 303 for a progressive enhancement form submission.
   * - In a Server Action, type defaults to 'push' and 'replace' elsewhere.
   *
   * Read more: [Next.js Docs: redirect](https://nextjs.org/docs/app/api-reference/functions/redirect)
   */
  export function redirect<RouteType>(
    /** The URL to redirect to */
    url: __next_route_internal_types__.RouteImpl<RouteType>,
    type?: RedirectType
  ): never;
  
  /**
   * This function allows you to redirect the user to another URL. It can be used in
   * [Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components),
   * [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers), and
   * [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations).
   *
   * - In a Server Component, this will insert a meta tag to redirect the user to the target page.
   * - In a Route Handler, it will serve a 308 to the caller.
   * - In a Server Action, it will perform a client-side navigation when JavaScript is available or serve a 303 for a progressive enhancement form submission.
   *
   * Read more: [Next.js Docs: redirect](https://nextjs.org/docs/app/api-reference/functions/redirect)
   */
  export function permanentRedirect<RouteType>(
    /** The URL to redirect to */
    url: __next_route_internal_types__.RouteImpl<RouteType>,
    type?: RedirectType
  ): never;
}

declare module 'next/form' {
  import type { FormProps as OriginalFormProps } from 'next/dist/client/form.js'

  type FormRestProps = Omit<OriginalFormProps, 'action'>

  export type FormProps<RouteInferType> = {
    /**
     * `action` can be either a `string` or a function.
     * - If `action` is a string, it will be interpreted as a path or URL to navigate to when the form is submitted.
     *   The path will be prefetched when the form becomes visible.
     * - If `action` is a function, it will be called when the form is submitted. See the [React docs](https://react.dev/reference/react-dom/components/form#props) for more.
     */
    action: __next_route_internal_types__.RouteImpl<RouteInferType> | ((formData: FormData) => void)
  } & FormRestProps

  export default function Form<RouteType>(props: FormProps<RouteType>): JSX.Element
}
