// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/account" | "/[locale]/account/leaderboard" | "/[locale]/account/orders" | "/[locale]/account/settings" | "/[locale]/admin" | "/[locale]/admin/ai" | "/[locale]/admin/ai/assistant" | "/[locale]/admin/ai/models" | "/[locale]/admin/blog" | "/[locale]/admin/blog/[id]" | "/[locale]/admin/bridge" | "/[locale]/admin/coupons" | "/[locale]/admin/orders" | "/[locale]/admin/orders/[id]" | "/[locale]/admin/payments" | "/[locale]/admin/payments/methods" | "/[locale]/admin/payments/transactions" | "/[locale]/admin/product-changes" | "/[locale]/admin/products" | "/[locale]/admin/products/[id]" | "/[locale]/admin/security/captcha" | "/[locale]/admin/security/login" | "/[locale]/admin/security/rate-limit" | "/[locale]/admin/settings/auth" | "/[locale]/admin/settings/backup" | "/[locale]/admin/settings/blog-sidebar" | "/[locale]/admin/settings/comments" | "/[locale]/admin/settings/goghdi" | "/[locale]/admin/settings/homepage" | "/[locale]/admin/settings/notice" | "/[locale]/admin/settings/seo" | "/[locale]/admin/settings/shipping" | "/[locale]/admin/settings/sms" | "/[locale]/admin/settings/stories" | "/[locale]/admin/settings/usd" | "/[locale]/admin/staff" | "/[locale]/admin/statistics" | "/[locale]/admin/uploads" | "/[locale]/admin/users" | "/[locale]/admin/vendors" | "/[locale]/blog" | "/[locale]/blog/[slug]" | "/[locale]/blog/category/[slug]" | "/[locale]/blog/seller/[sellerId]" | "/[locale]/blog/tag/[slug]" | "/[locale]/cart" | "/[locale]/checkout/[id]" | "/[locale]/contact-us" | "/[locale]/experts/[id]" | "/[locale]/login" | "/[locale]/orders/[id]" | "/[locale]/pay/local/[authority]" | "/[locale]/products" | "/[locale]/products/[slug]" | "/[locale]/seller-dashboard" | "/[locale]/seller-dashboard/blog/[id]" | "/[locale]/seller-dashboard/bridge" | "/[locale]/seller-dashboard/bridge/products/new" | "/[locale]/seller-dashboard/comments" | "/[locale]/seller-dashboard/products/new" | "/[locale]/staff-setup/[token]"
type AppRouteHandlerRoutes = "/[locale]/blog/feed.xml" | "/[locale]/blog/rss.xml" | "/api/auth/login-methods" | "/homepage-images/[filename]" | "/media/[assetId]/[filename]" | "/sitemap.xml" | "/sitemap/[id]"
type PageRoutes = never
type LayoutRoutes = "/[locale]" | "/[locale]/account" | "/[locale]/admin" | "/[locale]/seller-dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/[locale]": { "locale": string; }
  "/[locale]/account": { "locale": string; }
  "/[locale]/account/leaderboard": { "locale": string; }
  "/[locale]/account/orders": { "locale": string; }
  "/[locale]/account/settings": { "locale": string; }
  "/[locale]/admin": { "locale": string; }
  "/[locale]/admin/ai": { "locale": string; }
  "/[locale]/admin/ai/assistant": { "locale": string; }
  "/[locale]/admin/ai/models": { "locale": string; }
  "/[locale]/admin/blog": { "locale": string; }
  "/[locale]/admin/blog/[id]": { "locale": string; "id": string; }
  "/[locale]/admin/bridge": { "locale": string; }
  "/[locale]/admin/coupons": { "locale": string; }
  "/[locale]/admin/orders": { "locale": string; }
  "/[locale]/admin/orders/[id]": { "locale": string; "id": string; }
  "/[locale]/admin/payments": { "locale": string; }
  "/[locale]/admin/payments/methods": { "locale": string; }
  "/[locale]/admin/payments/transactions": { "locale": string; }
  "/[locale]/admin/product-changes": { "locale": string; }
  "/[locale]/admin/products": { "locale": string; }
  "/[locale]/admin/products/[id]": { "locale": string; "id": string; }
  "/[locale]/admin/security/captcha": { "locale": string; }
  "/[locale]/admin/security/login": { "locale": string; }
  "/[locale]/admin/security/rate-limit": { "locale": string; }
  "/[locale]/admin/settings/auth": { "locale": string; }
  "/[locale]/admin/settings/backup": { "locale": string; }
  "/[locale]/admin/settings/blog-sidebar": { "locale": string; }
  "/[locale]/admin/settings/comments": { "locale": string; }
  "/[locale]/admin/settings/goghdi": { "locale": string; }
  "/[locale]/admin/settings/homepage": { "locale": string; }
  "/[locale]/admin/settings/notice": { "locale": string; }
  "/[locale]/admin/settings/seo": { "locale": string; }
  "/[locale]/admin/settings/shipping": { "locale": string; }
  "/[locale]/admin/settings/sms": { "locale": string; }
  "/[locale]/admin/settings/stories": { "locale": string; }
  "/[locale]/admin/settings/usd": { "locale": string; }
  "/[locale]/admin/staff": { "locale": string; }
  "/[locale]/admin/statistics": { "locale": string; }
  "/[locale]/admin/uploads": { "locale": string; }
  "/[locale]/admin/users": { "locale": string; }
  "/[locale]/admin/vendors": { "locale": string; }
  "/[locale]/blog": { "locale": string; }
  "/[locale]/blog/[slug]": { "locale": string; "slug": string; }
  "/[locale]/blog/category/[slug]": { "locale": string; "slug": string; }
  "/[locale]/blog/feed.xml": { "locale": string; }
  "/[locale]/blog/rss.xml": { "locale": string; }
  "/[locale]/blog/seller/[sellerId]": { "locale": string; "sellerId": string; }
  "/[locale]/blog/tag/[slug]": { "locale": string; "slug": string; }
  "/[locale]/cart": { "locale": string; }
  "/[locale]/checkout/[id]": { "locale": string; "id": string; }
  "/[locale]/contact-us": { "locale": string; }
  "/[locale]/experts/[id]": { "locale": string; "id": string; }
  "/[locale]/login": { "locale": string; }
  "/[locale]/orders/[id]": { "locale": string; "id": string; }
  "/[locale]/pay/local/[authority]": { "locale": string; "authority": string; }
  "/[locale]/products": { "locale": string; }
  "/[locale]/products/[slug]": { "locale": string; "slug": string; }
  "/[locale]/seller-dashboard": { "locale": string; }
  "/[locale]/seller-dashboard/blog/[id]": { "locale": string; "id": string; }
  "/[locale]/seller-dashboard/bridge": { "locale": string; }
  "/[locale]/seller-dashboard/bridge/products/new": { "locale": string; }
  "/[locale]/seller-dashboard/comments": { "locale": string; }
  "/[locale]/seller-dashboard/products/new": { "locale": string; }
  "/[locale]/staff-setup/[token]": { "locale": string; "token": string; }
  "/api/auth/login-methods": {}
  "/homepage-images/[filename]": { "filename": string; }
  "/media/[assetId]/[filename]": { "assetId": string; "filename": string; }
  "/sitemap.xml": {}
  "/sitemap/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": never
  "/[locale]/account": never
  "/[locale]/admin": never
  "/[locale]/seller-dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
