// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/account/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/orders">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/settings">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/ai/assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/ai/assistant">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/ai/assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/ai/models/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/ai/models">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/ai/models/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/ai">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/blog/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/blog/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/blog/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/blog">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/bridge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/bridge">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/bridge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/coupons">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/payments/methods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/payments/methods">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/payments/methods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/payments">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/payments/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/payments/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/payments/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/product-changes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/product-changes">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/product-changes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/products/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/products/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/products/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/products">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/security/captcha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/security/captcha">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/security/captcha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/security/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/security/login">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/security/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/security/rate-limit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/security/rate-limit">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/security/rate-limit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/settings/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/auth">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/settings/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/settings/backup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/backup">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/settings/backup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/settings/blog-sidebar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/blog-sidebar">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/settings/blog-sidebar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/settings/comments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/comments">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/settings/comments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/settings/goghdi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/goghdi">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/settings/goghdi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/settings/homepage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/homepage">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/settings/homepage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/settings/notice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/notice">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/settings/notice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/settings/seo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/seo">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/settings/seo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/settings/shipping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/shipping">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/settings/shipping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/settings/sms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/sms">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/settings/sms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/settings/stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/stories">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/settings/stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/settings/usd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/usd">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/settings/usd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/staff">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/statistics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/statistics">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/statistics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/uploads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/uploads">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/uploads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/vendors">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/category/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/category/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/category/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/seller/[sellerId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/seller/[sellerId]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/seller/[sellerId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/tag/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/tag/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/tag/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cart">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/checkout/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/checkout/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/checkout/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/contact-us/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contact-us">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/contact-us/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/experts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/experts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/experts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/pay/local/[authority]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/pay/local/[authority]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/pay/local/[authority]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/products/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/products/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/seller-dashboard/blog/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/seller-dashboard/blog/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/seller-dashboard/blog/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/seller-dashboard/bridge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/seller-dashboard/bridge">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/seller-dashboard/bridge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/seller-dashboard/bridge/products/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/seller-dashboard/bridge/products/new">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/seller-dashboard/bridge/products/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/seller-dashboard/comments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/seller-dashboard/comments">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/seller-dashboard/comments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/seller-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/seller-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/seller-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/seller-dashboard/products/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/seller-dashboard/products/new">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/seller-dashboard/products/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/staff-setup/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/staff-setup/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/staff-setup/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/feed.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/blog/feed.xml">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/feed.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/rss.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/blog/rss.xml">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/rss.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login-methods/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login-methods">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login-methods/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/homepage-images/[filename]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/homepage-images/[filename]">> = Specific
  const handler = {} as typeof import("../../src/app/homepage-images/[filename]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/media/[assetId]/[filename]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/media/[assetId]/[filename]">> = Specific
  const handler = {} as typeof import("../../src/app/media/[assetId]/[filename]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sitemap.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap.xml">> = Specific
  const handler = {} as typeof import("../../src/app/sitemap.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sitemap/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/sitemap/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/[locale]/account/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/account">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/seller-dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/seller-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/seller-dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
