export const CONTENT_AI_COPY = {
  en: {
    title: "Writing assistant", intro: "Turn your notes into a draft. Check the facts, choose fields, then apply. Nothing is published automatically.",
    source: "Your notes or draft", sourceHint: "Include real specifications, limitations, and the points readers need to know. At least 20 characters.", current: "Use current content", keyword: "Focus keyword (optional)", audience: "Who is this for? (optional)", cover: "Describe the actual cover image (optional)", generate: "Generate draft", generating: "Writing…", retry: "Retry this language", ready: "Ready", failed: "Failed", waiting: "Waiting", preview: "Preview", fields: "Fields to apply", apply: "Apply selected fields", undo: "Undo application", applied: "Added to the editor. Review and save when ready.", changed: "The editor changed after generation started. Review your current edits before replacing fields.", reviewed: "I reviewed my edits; allow application", undoChanged: "Undo is unavailable because you edited the content after applying the draft.", notConfigured: "An administrator needs to assign a writing model before you can generate drafts.", error: "Generation failed. Your editor is unchanged; try again.", denied: "AI access is no longer available. Ask an administrator to check your permissions.", limited: "Too many AI requests. Wait a few minutes before retrying.", unavailable: "Could not check AI availability.", reload: "Check again", download: "Download HTML", review: "Check before saving", sourceLong: "Current content exceeds 16,000 characters. Shorten it before generating.", allLanguages: "Generates Persian, English and Arabic. Successful languages stay available if another fails.", partial: "Only ready languages will be applied. Retry failed languages to complete the article.", body: "Article body", description: "Description", titleField: "Title", slug: "Slug", excerpt: "Excerpt", seoTitle: "SEO title", seoDescription: "SEO description", coverAltText: "Cover alt text", category: "Category", tags: "Tags", noMatch: "No matching suggestion", sourceLanguage: "Output language", fa: "Persian", en: "English", ar: "Arabic"
  },
  fa: {
    title: "دستیار نوشتن", intro: "یادداشت‌ها را به پیش‌نویس تبدیل کنید. متن را بررسی و فیلدهای دلخواه را وارد ویرایشگر کنید. انتشار با شماست.",
    source: "یادداشت یا پیش‌نویس شما", sourceHint: "مشخصات واقعی، محدودیت‌ها و نکات مهم را بنویسید؛ حداقل ۲۰ نویسه.", current: "استفاده از متن فعلی", keyword: "عبارت کلیدی (اختیاری)", audience: "مخاطب این متن کیست؟ (اختیاری)", cover: "تصویر واقعی جلد را توصیف کنید (اختیاری)", generate: "ساخت پیش‌نویس", generating: "در حال نوشتن…", retry: "تلاش دوباره برای این زبان", ready: "آماده", failed: "ناموفق", waiting: "در انتظار", preview: "پیش‌نمایش", fields: "فیلدهای قابل جایگزینی", apply: "اعمال فیلدهای انتخاب‌شده", undo: "برگرداندن متن قبلی", applied: "متن وارد ویرایشگر شد. پس از بررسی، آن را ذخیره کنید.", changed: "از شروع ساخت پیش‌نویس، متن ویرایشگر تغییر کرده است. پیش از جایگزینی، ویرایش‌های خود را بررسی کنید.", reviewed: "ویرایش‌ها را بررسی کردم؛ اجازه جایگزینی", undoChanged: "پس از اعمال پیش‌نویس، متن را ویرایش کرده‌اید؛ بازگردانی مستقیم ممکن نیست.", notConfigured: "برای ساخت پیش‌نویس، مدیر باید یک مدل نویسندگی انتخاب کند.", error: "ساخت پیش‌نویس انجام نشد. متن ویرایشگر تغییر نکرده؛ دوباره تلاش کنید.", denied: "دسترسی هوش مصنوعی فعال نیست. از مدیر بخواهید دسترسی شما را بررسی کند.", limited: "تعداد درخواست‌ها زیاد است. چند دقیقه بعد دوباره تلاش کنید.", unavailable: "بررسی دسترسی هوش مصنوعی ممکن نبود.", reload: "بررسی دوباره", download: "دریافت HTML", review: "پیش از ذخیره بررسی کنید", sourceLong: "متن فعلی بیش از ۱۶٬۰۰۰ نویسه است. پیش از ساخت پیش‌نویس آن را کوتاه کنید.", allLanguages: "پیش‌نویس فارسی، انگلیسی و عربی ساخته می‌شود. اگر یک زبان ناموفق باشد، بقیه در دسترس می‌مانند.", partial: "فقط زبان‌های آماده اعمال می‌شوند. برای تکمیل مقاله، زبان‌های ناموفق را دوباره بسازید.", body: "متن مقاله", description: "توضیحات", titleField: "عنوان", slug: "نامک", excerpt: "خلاصه", seoTitle: "عنوان سئو", seoDescription: "توضیحات سئو", coverAltText: "متن جایگزین تصویر", category: "دسته‌بندی", tags: "برچسب‌ها", noMatch: "پیشنهاد مطابقی پیدا نشد", sourceLanguage: "زبان متن", fa: "فارسی", en: "انگلیسی", ar: "عربی"
  },
  ar: {
    title: "مساعد الكتابة", intro: "حوّل ملاحظاتك إلى مسودة. راجع الحقائق واختر الحقول ثم طبّقها. لا يُنشر شيء تلقائياً.",
    source: "ملاحظاتك أو مسودتك", sourceHint: "أضف المواصفات الفعلية والقيود والنقاط المهمة للقارئ. 20 حرفاً على الأقل.", current: "استخدام المحتوى الحالي", keyword: "العبارة الرئيسية (اختياري)", audience: "لمن تكتب؟ (اختياري)", cover: "صف صورة الغلاف الفعلية (اختياري)", generate: "إنشاء مسودة", generating: "جارٍ الكتابة…", retry: "إعادة محاولة هذه اللغة", ready: "جاهز", failed: "لم ينجح", waiting: "في الانتظار", preview: "معاينة", fields: "الحقول المطلوب تطبيقها", apply: "تطبيق الحقول المحددة", undo: "التراجع عن التطبيق", applied: "أُضيف النص إلى المحرر. راجعه ثم احفظه.", changed: "تغيّر المحرر منذ بدء الكتابة. راجع تعديلاتك قبل استبدال الحقول.", reviewed: "راجعت تعديلاتي؛ السماح بالتطبيق", undoChanged: "لا يمكن التراجع مباشرة لأنك عدّلت المحتوى بعد التطبيق.", notConfigured: "يجب أن يختار المسؤول نموذج كتابة قبل إنشاء المسودات.", error: "تعذر إنشاء المسودة. لم يتغير المحرر؛ حاول مجدداً.", denied: "صلاحية الذكاء الاصطناعي غير متاحة. اطلب من المسؤول مراجعتها.", limited: "طلبات كثيرة. انتظر بضع دقائق ثم حاول مجدداً.", unavailable: "تعذر التحقق من صلاحية الذكاء الاصطناعي.", reload: "تحقق مجدداً", download: "تنزيل HTML", review: "راجع قبل الحفظ", sourceLong: "يتجاوز المحتوى الحالي 16000 حرف. اختصره قبل إنشاء المسودة.", allLanguages: "ينشئ مسودات بالفارسية والإنجليزية والعربية. تبقى اللغات الناجحة متاحة إذا فشلت أخرى.", partial: "ستُطبّق اللغات الجاهزة فقط. أعد محاولة اللغات التي فشلت لإكمال المقال.", body: "نص المقال", description: "الوصف", titleField: "العنوان", slug: "المعرّف", excerpt: "الملخص", seoTitle: "عنوان البحث", seoDescription: "وصف البحث", coverAltText: "النص البديل للغلاف", category: "الفئة", tags: "الوسوم", noMatch: "لا يوجد اقتراح مطابق", sourceLanguage: "لغة النص", fa: "الفارسية", en: "الإنجليزية", ar: "العربية"
  }
};
