export const OVERVIEW_COPY = {
  en: {
    admin: "Business overview", seller: "Your store, at a glance", adminIntro: "Follow performance. Keep daily operations moving.", sellerIntro: "See how your store is doing and pick up your next task.",
    workspace: "Overview", thisWeek: "This week", thisMonth: "This month", days90: "90 days", period: "Reporting period", refresh: "Refresh", updating: "Updating…", report: "Full report", updated: "Updated", timezone: "Tehran time",
    sales: "Gross sales", income: "Commission earned", earnings: "Net earned", orders: "Paid orders", average: "Average order", previous: "vs. previous period", noComparison: "No previous activity", unchanged: "No change", trend: "Sales over time", trendHint: "Verified sales in the selected period", details: "Daily figures", date: "Date", amount: "Sales", empty: "No sales in this period", emptyHint: "Try a longer period or review your products and offers.",
    operations: "Your next move", operationsHint: "Go straight to the work that matters.", manageOrders: "Manage orders", ordersHint: "Review orders and fulfilment", products: "Manage products", productsHint: "Update your catalog and offers", vendors: "Manage sellers", vendorsHint: "Review seller access and accounts", payouts: "View payouts", payoutsHint: "Track settlements and balances", add: "Add product", newOrders: "new since your last visit", finances: "Settlement snapshot", liability: "Outstanding balance", liabilityHint: "Current balance across all periods", settled: "Settled in this period", refunds: "Refunded in this period", activity: "Recent financial activity", activityHint: "Latest entries in this period", noActivity: "No financial activity in this period.", leaders: "Best-selling products", leadersHint: "Ranked by sales in this period", noProducts: "Products appear here after a verified sale.", units: "units sold", sale: "Sale", refund: "Refund", payout: "Payout", loading: "Loading your overview…", error: "We couldn’t load your overview. Try again.", stale: "Refresh failed. Showing the last loaded period.", retry: "Try again", access: "Your workspace is ready", accessHint: "Use the shortcuts to manage your products, orders, and payouts.",
  },
  fa: {
    admin: "کسب‌وکار در یک نگاه", seller: "فروشگاه شما در یک نگاه", adminIntro: "روند فروش را ببینید و کارهای روزانه را پیگیری کنید.", sellerIntro: "از وضعیت فروشگاه باخبر شوید و کار بعدی را شروع کنید.",
    workspace: "نمای کلی", thisWeek: "این هفته", thisMonth: "این ماه", days90: "۹۰ روز", period: "بازه گزارش", refresh: "تازه‌سازی", updating: "در حال دریافت…", report: "گزارش کامل", updated: "آخرین به‌روزرسانی", timezone: "به وقت تهران",
    sales: "فروش ناخالص", income: "درآمد کارمزد", earnings: "درآمد خالص", orders: "سفارش پرداخت‌شده", average: "میانگین سفارش", previous: "نسبت به بازه قبل", noComparison: "بدون فعالیت در بازه قبل", unchanged: "بدون تغییر", trend: "روند فروش", trendHint: "فروش‌های تأییدشده در بازه انتخابی", details: "آمار روزانه", date: "تاریخ", amount: "فروش", empty: "در این بازه فروشی ثبت نشده", emptyHint: "بازه طولانی‌تری انتخاب کنید یا محصولات و پیشنهادهای فروش را بررسی کنید.",
    operations: "قدم بعدی شما", operationsHint: "مستقیم به سراغ کارهای فروشگاه بروید.", manageOrders: "مدیریت سفارش‌ها", ordersHint: "بررسی و پیگیری سفارش‌ها", products: "مدیریت محصولات", productsHint: "ویرایش کاتالوگ و پیشنهادهای فروش", vendors: "مدیریت فروشندگان", vendorsHint: "بررسی حساب‌ها و دسترسی فروشندگان", payouts: "مشاهده تسویه‌ها", payoutsHint: "پیگیری تسویه‌ها و مانده حساب", add: "افزودن محصول", newOrders: "جدید از آخرین بازدید شما", finances: "وضعیت تسویه", liability: "مانده تسویه‌نشده", liabilityHint: "مانده فعلی در تمام بازه‌ها", settled: "تسویه‌شده در این بازه", refunds: "بازپرداخت در این بازه", activity: "تازه‌ترین فعالیت‌های مالی", activityHint: "آخرین موارد ثبت‌شده در این بازه", noActivity: "در این بازه فعالیت مالی ثبت نشده است.", leaders: "پرفروش‌ترین محصولات", leadersHint: "بر اساس مبلغ فروش در این بازه", noProducts: "محصولات پس از اولین فروش تأییدشده اینجا نمایش داده می‌شوند.", units: "عدد فروش", sale: "فروش", refund: "بازپرداخت", payout: "تسویه", loading: "در حال دریافت نمای کلی…", error: "دریافت اطلاعات انجام نشد. دوباره تلاش کنید.", stale: "تازه‌سازی انجام نشد. اطلاعات آخرین بازه دریافت‌شده نمایش داده می‌شود.", retry: "تلاش دوباره", access: "آماده شروع کار هستید", accessHint: "از میان‌برها برای مدیریت محصولات، سفارش‌ها و تسویه‌ها استفاده کنید.",
  },
  ar: {
    admin: "أعمالك في لمحة", seller: "متجرك في لمحة", adminIntro: "تابع الأداء وأنجز أعمالك اليومية.", sellerIntro: "اطّلع على أداء متجرك وابدأ مهمتك التالية.",
    workspace: "نظرة عامة", thisWeek: "هذا الأسبوع", thisMonth: "هذا الشهر", days90: "90 يوماً", period: "فترة التقرير", refresh: "تحديث", updating: "جارٍ التحديث…", report: "التقرير الكامل", updated: "آخر تحديث", timezone: "بتوقيت طهران",
    sales: "إجمالي المبيعات", income: "دخل العمولة", earnings: "صافي الدخل", orders: "الطلبات المدفوعة", average: "متوسط الطلب", previous: "مقارنة بالفترة السابقة", noComparison: "لا يوجد نشاط سابق", unchanged: "دون تغيير", trend: "اتجاه المبيعات", trendHint: "المبيعات المؤكدة خلال الفترة المحددة", details: "الأرقام اليومية", date: "التاريخ", amount: "المبيعات", empty: "لا توجد مبيعات في هذه الفترة", emptyHint: "اختر فترة أطول أو راجع منتجاتك وعروضك.",
    operations: "خطوتك التالية", operationsHint: "انتقل مباشرة إلى أعمالك اليومية.", manageOrders: "إدارة الطلبات", ordersHint: "مراجعة الطلبات وتنفيذها", products: "إدارة المنتجات", productsHint: "تحديث الكتالوج والعروض", vendors: "إدارة البائعين", vendorsHint: "مراجعة الحسابات والصلاحيات", payouts: "عرض الدفعات", payoutsHint: "متابعة التسويات والأرصدة", add: "إضافة منتج", newOrders: "جديدة منذ زيارتك الأخيرة", finances: "ملخص التسويات", liability: "الرصيد المعلّق", liabilityHint: "الرصيد الحالي لجميع الفترات", settled: "تسويات هذه الفترة", refunds: "مبالغ مستردة في هذه الفترة", activity: "آخر النشاطات المالية", activityHint: "أحدث السجلات في هذه الفترة", noActivity: "لا يوجد نشاط مالي في هذه الفترة.", leaders: "المنتجات الأكثر مبيعاً", leadersHint: "حسب المبيعات في هذه الفترة", noProducts: "تظهر المنتجات هنا بعد أول عملية بيع مؤكدة.", units: "وحدات مباعة", sale: "بيع", refund: "استرداد", payout: "تسوية", loading: "جارٍ تحميل النظرة العامة…", error: "تعذر تحميل المعلومات. حاول مجدداً.", stale: "فشل التحديث. نعرض آخر فترة تم تحميلها.", retry: "حاول مجدداً", access: "مساحة عملك جاهزة", accessHint: "استخدم الاختصارات لإدارة المنتجات والطلبات والدفعات.",
  },
} as const;
