var R=require("../../chunks/[turbopack]_runtime.js")("server/app/robots.txt/route.js")
R.c("server/chunks/[root-of-the-server]__03or08k._.js")
R.c("server/chunks/1boe_next_0evwo43._.js")
R.c("server/chunks/_0vwlqbm._.js")
R.c("server/chunks/1boe_next_dist_10iryjh._.js")
R.c("server/chunks/[root-of-the-server]__19m4cq4._.js")
R.c("server/chunks/1boe_next_dist_0eeo8qn._.js")
R.c("server/chunks/apps_web__next-internal_server_app_robots_txt_route_actions_0m5_h79.js")
R.m(47002)
module.exports=R.m(47002).exports
