"use client";

import Link from "next/link";
import { useMemo, useState, type FormEvent } from "react";
import { api } from "@/lib/api/client";
import type { Locale } from "@/lib/i18n";
import styles from "./BridgeWorkspace.module.css";

export type StoreProduct = { id: string; slug: string; title: string; description: string | null; category: string | null; type: string; bridge?: { fields: Array<{ key: string; label: string; type: "text"|"textarea"|"number"|"select"; required: boolean; placeholder?: string; helpText?: string; minimumLength?: number; maximumLength?: number; options?: Array<{ value: string; label: string }> }>; minimumQuantity: number; maximumQuantity: number }; variants: Array<{ id: string; name: string | null; offers: Array<{ id: string; price: string; currency: string; seller: { shopName: string } }> }> };

const COPY = {
  en: { back: "TopGSM", service: "Secure service checkout", sold: "Sold by", variant: "Offer", qty: "Quantity", buyer: "Required information", buy: "Buy now", signin: "Verify your mobile", phone: "Iranian mobile number", fullName: "Full name", email: "Email", code: "Six-digit code", send: "Send code", verify: "Verify and continue", sending: "Please wait…", total: "Total", protected: "Your inputs are encrypted and sent only for fulfilling this order.", error: "Checkout could not continue. Review the information and try again.", unavailable: "This product is currently unavailable." },
  fa: { back: "تاپ جی‌اس‌ام", service: "خرید امن سرویس", sold: "فروشنده", variant: "پیشنهاد", qty: "تعداد", buyer: "اطلاعات مورد نیاز", buy: "خرید مستقیم", signin: "تأیید شماره موبایل", phone: "شماره موبایل ایران", fullName: "نام و نام خانوادگی", email: "ایمیل", code: "کد شش‌رقمی", send: "ارسال کد", verify: "تأیید و ادامه", sending: "کمی صبر کنید…", total: "مبلغ کل", protected: "اطلاعات شما رمزنگاری می‌شود و فقط برای انجام همین سفارش استفاده خواهد شد.", error: "ادامه پرداخت ممکن نبود. اطلاعات را بررسی و دوباره تلاش کنید.", unavailable: "این محصول اکنون قابل خرید نیست." },
  ar: { back: "TopGSM", service: "شراء خدمة آمن", sold: "البائع", variant: "العرض", qty: "الكمية", buyer: "المعلومات المطلوبة", buy: "اشتر الآن", signin: "تحقق من رقم الجوال", phone: "رقم جوال إيراني", fullName: "الاسم الكامل", email: "البريد الإلكتروني", code: "الرمز المكوّن من ستة أرقام", send: "إرسال الرمز", verify: "تحقق وتابع", sending: "يرجى الانتظار…", total: "الإجمالي", protected: "تُشفّر بياناتك ولا تُستخدم إلا لتنفيذ هذا الطلب.", error: "تعذر متابعة الدفع. راجع المعلومات وحاول مجدداً.", unavailable: "هذا المنتج غير متاح حالياً." }
} as const;

export function BridgeCheckout({ locale, product, signedInBuyer }: { locale: Locale; product: StoreProduct; signedInBuyer: boolean }) {
  const c=COPY[locale]; const offers=product.variants.flatMap((variant)=>variant.offers.map((offer)=>({...offer,variantName:variant.name})));
  const [offerId,setOfferId]=useState(offers[0]?.id ?? ""); const [quantity,setQuantity]=useState(product.bridge?.minimumQuantity ?? 1); const [fields,setFields]=useState<Record<string,string>>({});
  const [otp,setOtp]=useState(signedInBuyer); const [challenge,setChallenge]=useState(""); const [phone,setPhone]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const offer=offers.find((item)=>item.id===offerId); const total=useMemo(()=>offer ? (BigInt(offer.price)*BigInt(quantity)).toLocaleString(locale) : "—",[offer,quantity,locale]);
  async function placeOrder() { if(!offer) return; const orderKey=crypto.randomUUID(); const order=await api.post<{id:string}>("/orders",{offerId:offer.id,quantity,bridgeFields:Object.entries(fields).map(([key,value])=>({key,value}))},{headers:{"Idempotency-Key":orderKey}}); const payment=await api.post<{paymentUrl:string}>("/payments/zarinpal",{orderId:order.data.id},{headers:{"Idempotency-Key":crypto.randomUUID()}}); window.location.assign(payment.data.paymentUrl); }
  async function submit(event:FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { if(!otp){ const form=new FormData(event.currentTarget); if(!challenge){ const result=await api.post<{challengeId:string}>("/auth/otp/request",{phoneNumber:phone}); setChallenge(result.data.challengeId); setBusy(false); return; } await api.post("/auth/otp/verify",{phoneNumber:phone,challengeId:challenge,code:form.get("code"),fullName:form.get("fullName"),email:form.get("email")}); setOtp(true); } await placeOrder(); } catch { setError(c.error); setBusy(false); } }
  if(!product.bridge || !offer) return <div className={styles.shell}><p className={styles.empty}>{c.unavailable}</p></div>;
  return <div className={styles.shell}><header className={styles.header}><div><p className={styles.brand}>{c.service}</p><h1>{product.title}</h1></div><div><p>{product.description}</p><Link className={styles.link} href={`/${locale}`}>{c.back}</Link></div></header><main className={styles.main}><form className={styles.form} onSubmit={submit} aria-busy={busy}>
    <div className={styles.formGrid}><label className={styles.field}><span>{c.variant}</span><select value={offerId} onChange={(e)=>setOfferId(e.target.value)}>{offers.map((item)=><option key={item.id} value={item.id}>{item.variantName || product.title} · {item.seller.shopName} · {Number(item.price).toLocaleString(locale)} {item.currency}</option>)}</select><small>{c.sold}: {offer.seller.shopName}</small></label><label className={styles.field}><span>{c.qty}</span><input type="number" min={product.bridge.minimumQuantity} max={product.bridge.maximumQuantity} value={quantity} onChange={(e)=>setQuantity(Number(e.target.value))} required/><small>{product.bridge.minimumQuantity}–{product.bridge.maximumQuantity}</small></label></div>
    <section className={styles.section}><div className={styles.sectionHead}><div><h2>{c.buyer}</h2><p>{c.protected}</p></div></div><div className={styles.formGrid}>{product.bridge.fields.map((field)=><label className={styles.field} key={field.key}><span>{field.label}{field.required?" *":""}</span>{field.type==="select"?<select required={field.required} value={fields[field.key]??""} onChange={(e)=>setFields((v)=>({...v,[field.key]:e.target.value}))}><option value=""/>{field.options?.map((o)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:field.type==="textarea"?<textarea required={field.required} minLength={field.minimumLength} maxLength={field.maximumLength} placeholder={field.placeholder} value={fields[field.key]??""} onChange={(e)=>setFields((v)=>({...v,[field.key]:e.target.value}))}/>:<input type={field.type==="number"?"number":"text"} required={field.required} minLength={field.minimumLength} maxLength={field.maximumLength} placeholder={field.placeholder} value={fields[field.key]??""} onChange={(e)=>setFields((v)=>({...v,[field.key]:e.target.value}))}/>}<small>{field.helpText??" "}</small></label>)}</div></section>
    {!otp?<section className={styles.section}><div className={styles.sectionHead}><h2>{c.signin}</h2></div><div className={styles.formGrid}><label className={styles.field}><span>{c.phone}</span><input type="tel" value={phone} onChange={(e)=>setPhone(e.target.value)} pattern="(?:\+98|0098|98|0)?9[0-9]{9}" required/><small>&nbsp;</small></label>{challenge?<><label className={styles.field}><span>{c.code}</span><input name="code" inputMode="numeric" pattern="[0-9]{6}" required/><small>&nbsp;</small></label><label className={styles.field}><span>{c.fullName}</span><input name="fullName" minLength={2} maxLength={120}/><small>&nbsp;</small></label><label className={styles.field}><span>{c.email}</span><input name="email" type="email" maxLength={254}/><small>&nbsp;</small></label></>:null}</div></section>:null}
    <div className={styles.cardHead}><strong>{c.total}: {total} {offer.currency}</strong><button className={styles.button} disabled={busy}>{busy?c.sending:!otp&&!challenge?c.send:!otp?c.verify:c.buy}</button></div>{error?<p className={styles.error} role="alert">{error}</p>:null}
  </form></main></div>;
}
