var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1l2lh7n._.js")
R.c("server/chunks/ssr/1boe_next_dist_0ocrfii._.js")
R.c("server/chunks/ssr/[root-of-the-server]__11-f4bz._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1vhqqby._.js")
R.c("server/chunks/ssr/1boe_next_dist_compiled_@opentelemetry_api_index_1uvc2-s.js")
R.c("server/chunks/ssr/1boe_next_dist_client_components_builtin_global-error_1k2mh8v.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app__global-error_page_actions_1vxuwj7.js")
R.m(26893)
module.exports=R.m(26893).exports
